name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Atau branch lain yang sesuai dengan kebutuhan Anda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Langkah 1: Check out kode repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Langkah 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Langkah 3: Log in ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}  # Gunakan secret Docker Hub username
        password: ${{ secrets.ACCESS }}  # Gunakan secret Docker Hub password

    # Langkah 4: Build Docker image dengan tag terbaru
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.USERNAME }}/uas-pcc-jul -f Dockerfile .

    # Langkah 5: Push Docker image ke Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.USERNAME }}/uas-pcc-jul:v2
